export const caseStudies = [
  {
    id: "x-growth",
    title: "X (Twitter) Growth Strategy",
    subtitle: "AARRR Funnel Optimization",
    tags: ["Growth", "AARRR", "Strategy"],
    filterCategory: "User acquisition",
    metric: "129.6",
    metricLabel: "Top RICE Score",
    summary: "A comprehensive end-to-end product strategy dissecting X's acquisition, activation, and retention bottlenecks to unlock scalable growth.",
    url: "/x-growth.html",
    liveUrl: "https://x-reimagined-c02fzlf9g-anish-shankar-s-projects.vercel.app/",
    liveLabel: "Live Prototype",
    themeColor: "#1D9BF0",
    themeSecondary: "#71C9F8",
    image: "/assets/x.svg"
  },
  {
    id: "spot-ride",
    title: "SPOT Ride",
    subtitle: "Solving Pickup Confusion",
    tags: ["0 to 1", "UX Research", "Logistics"],
    filterCategory: "PRD",
    metric: "42%",
    metricLabel: "Drop in Cancellations",
    summary: "A 0-to-1 product feature designed to eliminate rider-driver pickup location ambiguity using verified micro-landmarks and directional routing.",
    url: "/spot-ride.html",
    themeColor: "#8B5CF6",
    themeSecondary: "#A78BFA",
    image: "/assets/uber.svg"
  },
  {
    id: "zepto",
    title: "Zepto: Increasing AOV",
    subtitle: "Growth & Gamification Strategy",
    tags: ["Growth", "Gamification", "AOV"],
    filterCategory: "Growth",
    metric: "18-24%",
    metricLabel: "Projected AOV Lift",
    summary: "Strategic interventions using 'Mystery Streaks', Smart Cart Builders, and FOMO mechanics to drive basket sizes up without compromising delivery speed.",
    url: "/zepto.html",
    themeColor: "#521292",
    themeSecondary: "#D4B2FF",
    image: "/assets/zepto.svg"
  },
  {
    id: "zomato",
    title: "Zomato Trust & Reliability",
    subtitle: "Gamification & Community",
    tags: ["Retention", "Gamification", "OKRs"],
    filterCategory: "Engagement and retention",
    metric: "35%",
    metricLabel: "D30 Retention Lift",
    summary: "Improving food ordering reliability and driving repeat orders through community challenges, squad leaderboards, and personalized experiences.",
    url: "/zomato.html",
    themeColor: "#E23744",
    themeSecondary: "#F07B83",
    image: "/assets/zomato.svg"
  },
  {
    id: "jtbd",
    title: "Food Scheduling Analysis",
    subtitle: "Jobs-to-be-Done Framework",
    tags: ["JTBD", "User Psychology", "Strategy"],
    filterCategory: "Product teardown",
    metric: "9",
    metricLabel: "Core User Jobs",
    summary: "Deep-dive analysis into why users schedule food orders, mapping the cognitive friction points, and proposing calendar integrations.",
    url: "/jtbd.html",
    themeColor: "#F59E0B",
    themeSecondary: "#FBBF24",
    image: "/assets/swiggy.svg"
  },
  {
    id: "vita-fit",
    title: "Vita Fit Community Challenges",
    subtitle: "Product Requirements Document",
    tags: ["PRD", "Social Features", "Monetization"],
    filterCategory: "PRD",
    metric: "25%",
    metricLabel: "New Squad Formation",
    summary: "End-to-end PRD for a new gamification engine transforming a solo fitness app into a highly retentive social-competitive ecosystem.",
    url: "/vita-fit.html",
    themeColor: "#D92525",
    themeSecondary: "#F87171",
    image: "/assets/vitafit.svg"
  },
  {
    id: "growgrid",
    title: "GrowGrid AI Learning",
    subtitle: "Recommendation Engine Architecture",
    tags: ["AI/ML", "System Design", "EdTech"],
    filterCategory: "PRD",
    metric: "30%",
    metricLabel: "Higher Completion",
    summary: "Architecting a personalized, AI-driven course recommendation engine balancing learner difficulty, skill gap analysis, and employability outcomes.",
    url: "/growgrid.html",
    themeColor: "#148F77",
    themeSecondary: "#45B39D",
    image: "/assets/growgrid.svg"
  },
  {
    id: "amazon-ux",
    title: "Amazon Checkout Redesign",
    subtitle: "UX Evaluation & Heuristics",
    tags: ["UX Design", "Heuristics", "E-commerce"],
    filterCategory: "Product teardown",
    metric: "400ms",
    metricLabel: "Feedback Latency",
    summary: "Applying Hick's Law, Tesler's Law, and UX heuristics to streamline Amazon's checkout flow, reducing cognitive load and error recovery friction.",
    url: "/amazon-ux.html",
    themeColor: "#FF9900",
    themeSecondary: "#FFB84D",
    image: "/assets/amazon.svg"
  }
];
